var mongoose = require('mongoose')
const AutoIncrement = require('mongoose-sequence')(mongoose);

const Schema = mongoose.Schema;

const employeeSchema = new Schema({
    employeeAutoGeneratedID: {
        type: Number
    },
    employeeID: {
        type: String
    },
    employeeName: {
        type: String,
        required: true
    },
    employeeEmail: {
        type: String,
    },
    CountryCode: {
        type: String,
    },
    employeePhoneNumber: {
        type: String,
    },
    employeeRoleID: {
        type: Number
    },
    updatedBy: {
        type: Number
    },
    updatedTime: {
        type: Date
    },
    createdTime: {
        type: Date,
        default: Date.now
    },
    status: {
        type: Boolean,
        default: true
    }
});


employeeSchema.plugin(AutoIncrement, { inc_field: 'employeeAutoGeneratedID' });

const employeeModel = mongoose.model('employee', employeeSchema);

module.exports = employeeModel;

