var adminCtrl = require('./adminCtrl');
var auth = require('../../utils/Auth').token;


module.exports = (app) => {

    app.post('/flyingbyts/api/user/getadmindetails', auth, adminCtrl.getAdminDetails);
    app.get('/flyingbyts/api/admin/getcustomerlist', auth, adminCtrl.getCustomerList);

    app.post('/flyingbyts/api/admin/addBabyDetails', auth, adminCtrl.addBabyDetails);
    app.get('/flyingbyts/api/admin/getBabyDetails/:customerID', auth, adminCtrl.getBabyDetails);
    app.get('/flyingbyts/api/admin/getAllBabyDetails', auth, adminCtrl.getAllBabyDetails);
    app.put('/flyingbyts/api/admin/updateBabyDetails/:babyID', auth, adminCtrl.updateBabyDetails);
    app.delete('/flyingbyts/api/admin/deleteBabyDetails/:babyID', auth, adminCtrl.deleteBabyDetails);

    app.get('/flyingbyts/api/admin/getCustomerPaymentDetails', auth, adminCtrl.getCustomerPaymentDetails);

    app.delete('/flyingbyts/api/admin/deleteCustomer/:customerID', auth, adminCtrl.deleteCustomer);


    app.post('/flyingbyts/api/admin/addEmployee', auth, adminCtrl.addEmployee);
    app.get('/flyingbyts/api/admin/getEmployee', auth, adminCtrl.getEmployee);
    app.put('/flyingbyts/api/admin/UpdateEmployee/:employeeAutoGeneratedID', auth, adminCtrl.UpdateEmployee);
    app.delete('/flyingbyts/api/admin/deleteEmployee/:employeeAutoGeneratedID', auth, adminCtrl.deleteEmployee);

}