var hospitalManagementCtrl = require('./hospitalManagementCtrl');
var auth = require('../../utils/Auth').token;


module.exports = (app) => {

    app.get('/flyingbyts/api/user/getCountryName', auth, hospitalManagementCtrl.getCountryName);
    app.get('/flyingbyts/api/user/getStateName/:country_id', auth, hospitalManagementCtrl.getStateName);
    app.get('/flyingbyts/api/user/getCityName/:state_id', auth, hospitalManagementCtrl.getCityName);

    app.post('/flyingbyts/api/user/addRole', auth, hospitalManagementCtrl.addRole);
    app.get('/flyingbyts/api/user/getRole', auth, hospitalManagementCtrl.getRole);
    app.put('/flyingbyts/api/user/UpdateRole/:roleID', auth, hospitalManagementCtrl.UpdateRole);
    app.delete('/flyingbyts/api/user/deleteRole/:roleID', auth, hospitalManagementCtrl.deleteRole);

    app.post('/flyingbyts/api/user/addEmployee', auth, hospitalManagementCtrl.addEmployee);
    app.get('/flyingbyts/api/user/getEmployee', auth, hospitalManagementCtrl.getEmployee);
    app.put('/flyingbyts/api/user/UpdateEmployee/:employeeAutoGeneratedID', auth, hospitalManagementCtrl.UpdateEmployee);
    app.delete('/flyingbyts/api/user/deleteEmployee/:employeeAutoGeneratedID', auth, hospitalManagementCtrl.deleteEmployee);

    app.post('/flyingbyts/api/user/addDoctorSpecialization', auth, hospitalManagementCtrl.addDoctorSpecialization);
    app.get('/flyingbyts/api/user/getDoctorSpecialization', auth, hospitalManagementCtrl.getDoctorSpecialization);
    app.put('/flyingbyts/api/user/UpdateDoctorSpecialization/:specializationID', auth, hospitalManagementCtrl.UpdateDoctorSpecialization);
    app.delete('/flyingbyts/api/user/deleteDoctorSpecialization/:specializationID', auth, hospitalManagementCtrl.deleteDoctorSpecialization);


    app.post('/flyingbyts/api/user/addDoctorQualification', auth, hospitalManagementCtrl.addDoctorQualification);
    app.get('/flyingbyts/api/user/getDoctorQualification', auth, hospitalManagementCtrl.getDoctorQualification);
    app.put('/flyingbyts/api/user/UpdateDoctorQualification/:DoctorQualificationID', auth, hospitalManagementCtrl.UpdateDoctorQualification);
    app.delete('/flyingbyts/api/user/deleteDoctorQualification/:DoctorQualificationID', auth, hospitalManagementCtrl.deleteDoctorQualification);

    app.post('/flyingbyts/api/user/addHospitalDetails', auth, hospitalManagementCtrl.addHospitalDetails);
    app.get('/flyingbyts/api/user/getHospitalDetails',  hospitalManagementCtrl.getHospitalDetails);
    app.put('/flyingbyts/api/user/UpdateHospitalDetails/:HospitalID', auth, hospitalManagementCtrl.UpdateHospitalDetails);
    app.delete('/flyingbyts/api/user/deleteHospitalDetails/:HospitalID', auth, hospitalManagementCtrl.deleteHospitalDetails);

    app.post('/flyingbyts/api/user/addHospitalBranchDetails', auth, hospitalManagementCtrl.addHospitalBranchDetails);
    app.get('/flyingbyts/api/user/getHospitalBranchDetails', auth, hospitalManagementCtrl.getHospitalBranchDetails);
    app.put('/flyingbyts/api/user/UpdateHospitalBranchDetails/:HospitalBranchID', auth, hospitalManagementCtrl.UpdateHospitalBranchDetails);
    app.delete('/flyingbyts/api/user/deleteHospitalBranchDetails/:HospitalBranchID', auth, hospitalManagementCtrl.deleteHospitalBranchDetails);

    app.post('/flyingbyts/api/user/addDoctorDetails', auth, hospitalManagementCtrl.addDoctorDetails);
    app.get('/flyingbyts/api/user/getDoctorDetails',  hospitalManagementCtrl.getDoctorDetails);
    app.put('/flyingbyts/api/user/UpdateDoctorDetails/:doctorDetailsID', auth, hospitalManagementCtrl.UpdateDoctorDetails);
    app.delete('/flyingbyts/api/user/deleteDoctorDetails/:doctorDetailsID', auth, hospitalManagementCtrl.deleteDoctorDetails);

    app.post('/flyingbyts/api/user/addDoctorAssignment', auth, hospitalManagementCtrl.addDoctorAssignment);
    app.get('/flyingbyts/api/user/getDoctorAssignment', auth, hospitalManagementCtrl.getDoctorAssignment);
    app.put('/flyingbyts/api/user/UpdateDoctorAssignment/:doctorAssignmentID', auth, hospitalManagementCtrl.UpdateDoctorAssignment);
    app.delete('/flyingbyts/api/user/deleteDoctorAssignment/:doctorAssignmentID', auth, hospitalManagementCtrl.deleteDoctorAssignment);

}


