pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "manu348/front:latest"
        DOCKER_USERNAME = "manu348"
        DOCKER_TOKEN = "dckr_pat_cMdGWRpjOwzGG4MiiIYq3w6uWHk"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/bathulamanu/cryvault-frontend.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_IMAGE ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh "echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh "docker push $DOCKER_IMAGE"
            }
        }

        stage('Run Docker Container') {
            steps {
                sh "docker stop cryvault-frontend || true && docker rm cryvault-frontend || true"
                sh "docker run -d --
