var mongoose = require('mongoose')
const AutoIncrement = require('mongoose-sequence')(mongoose);

const Schema = mongoose.Schema;


const employeeSchema = new Schema({
    employeeAutoGeneratedID: {
        type: Number
    },
    employeeID: {
        type: String,
        required: true
    },
    firstName: {
        type: String,
        required: true
    },
    lastName: {
        type: String
    },
    email: {
        type: String,
        required: true
    },
    password:{
        type: String
    },
    countryCode: {
        type: String,
        required: true
    },
    PhoneNumber: {
        type: String,
        required: true
    },
    roleID: {
        type: Number,
        required: true
    },
    profilePhoto: {
        type: String,
        default: ""
    },
    createdBy: {
        type: Number
    },
    updatedBy: {
        type: Number
    },
    updatedTime: {
        type: Date
    },
    createdTime: {
        type: Date,
        default: Date.now
    },
    status: {
        type: Boolean,
        default: true
    }
});


employeeSchema.plugin(AutoIncrement, { inc_field: 'employeeAutoGeneratedID' });

const employeeModel = mongoose.model('employee', employeeSchema);

module.exports = employeeModel;

